# 設定項目の説明は https://github.com/tsukumijima/KonomiTV/blob/master/config.example.yaml をごらんください。
# コンテナイメージ作者のテスト環境固有の設定が含まれているため、そのままでは使えません。
general:
  backend: "Mirakurun"
  edcb_url: "tcp://localhost:4510/" # ignored
  mirakurun_url: "http://192.168.10.13:40772/"
  encoder: "FFmpeg"
  program_update_interval: 5 # minutes
  debug: false
  debug_encoder: false
server:
  port: 7000
  custom_https_certificate: null
  custom_https_private_key: null
tv:
  max_alive_time: 10 # seconds
  debug_mode_ts_path: null
video:
  recorded_folders: ["/"] # relative path from /host-rootfs
capture:
  upload_folder: "/" # relative path from /host-rootfs
