
name: Build and Publish Container Image

# タグが作成されたとき or 手動実行
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

# ジョブの定義
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to the Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract Metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/hrko/konomitv-lite
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Prune Untagged Docker Images
        uses: vlaurin/action-ghcr-prune@v0.5.0
        with:
          token: ${{ secrets.DELETE_GHCR_IMAGES_TOKEN }}
          container: konomitv
          dry-run: false
          prune-untagged: true
